# Generated by Django 3.0.3 on 2020-05-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompreferences',
            name='preferences',
            field=models.TextField(blank=True, default='beaches', max_length=1600),
        ),
    ]
