# Generated by Django 3.0.3 on 2020-05-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200512_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompreferences',
            name='preferences',
            field=models.TextField(blank=True, default='beaches', max_length=120),
        ),
    ]
