# Generated by Django 3.0.5 on 2020-05-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_destination_typeofplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.CharField(default='hyderabad', max_length=200),
            preserve_default=False,
        ),
    ]
